# Site settings
title: Pradyumna's CV 
description: pradyumnac's CV
favicon: /assets/img/avatar.JPG
baseurl: https://pradyumnac.github.io/resumecard
url: https://pradyumnac.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-102177899-2

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Pradyumna Chatterjee
  title: Python Developer
  address: Kolkata, India
  email: pady92#gmail[dot]com
  link: https://pradyumnac.github.io
  weibo:
  github: pradyumnac
  linkedin: pradyumnac
  twitter: pradyumnacster
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Independant Consultant
      location: Kolkata, India
      title: Devops Engineer
      started: August 2017
      duration: (Aug, 2017 - present)
      description: I am currently working as a Consultant Devops Engineer for various clients primarily using Python, Google App Engine and Google CLoud APis. aI am also wortking on a personal project to educate and bring Machine learning accessible to the younger associates in my industry
    - work2:
      company: Cognizant Technology Solutions Limited
      location: Kolkata, India
      title: Automation Engineer (UFT & Selenium)
      started: 2013
      duration: (2013 - Aug, 2017)
      description: I have worked extensively with US based Insurance Gianys on developing Autmation Testing Solutions using UFT, Selenium and SOAP UI Automation. My domain of expertise in the role was Web testing & Automation Testing
    - work3:
      company: Aptsource Software Private Limited
      location: Kolkata, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I have worked as a Full Stack Developer for US based clients on Ecommerce and Hospital Manage.ment domains. My primary language was Python/Django Framework. I have worked as a full stack developer working on Python, Javascript & Postgres. I have wokred on some parts of J2EE/Java based Struts framework  as part of my role in the company
  educationHistory:
    - education1:
      organization: St. Thomas College of Engineering & Technology
      location: Kolkata, India
      degree: Bachelor
      major: Computer Science
      started: 2009
      duration: (2009 - 2012)
      description: I have pursued B. Tech. (Graduation) in Computer Science and Engineering with Specialisation in Image Processing and Computer Vision
  languages:
    - language1:
      name: English
      proficiency: Professional
    - language2:
      name: Hindi
      proficiency: Professional
    - language3:
      name: German
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: Python
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 80%
    - skill3:
      name: JavaScript
      percentage: 80%
    - skill4:
      name: Google App Engine
      percentage: 50%
    - skill5:
      name: Machine Learning
      percentage: 50%
